### ISSUE TITLE
Adding background corrected images to default features

### ISSUE THREAD

**Issue by maxschloegel** [DC-analysis/dclab#170]
Background corrected images are essential for the training of Neural Networks.
In the future we should add the step to compute the background corrected images to the aquisition pipeline. As this is a more complex task and will take more time to implement, I would like to suggest an interim solution, which could also be needed at a later stage.

Currently it is necessary to load the  background corrected images via PluginFeature or a TemporaryFeature  to be able to access the background corrected images in the RTDC_HDF5, even though they are already contained in the HDF5-file.
I would suggest to add the non-scalar feature "image_bg_corr" (definitely open to discussion about the name) to load the background corrected images by defafult, if present in the HDF5-file (similar to "image_bg").

This might be closely related to the storing of the predicted `ml_score_`-features in an external file. A larger difference is, though, that the background corrected image should be fix and would not be updated by a new model/way of computation.

**Comment by paulmueller** [comment]
Just a few general comments:

1. We currently have two ways of doing background correction

(A) by Shape-In (error-prone if not enough empty frames are available (horizontal white stripe)) and

(B) post-processing using rolling median filter (more stable) via plugin feature by @maxschloegel.

2. Adding bg image correction to the acquisition pipeline drastically increases file size. It would make more sense to do this in post-processing only. Maybe store this information in **a**n**c**illary files (*.acdc) that don't have to be stored in the same location and that don't require modifying raw data files -> new issue?

3. Adding a background-corrected image feature (maybe "image_bc"?) as an ancillary feature makes sense. It is computed if "image" and "image_bg" are available and if "image_bc" is already present in the HDF5 file, then this is used.

**Comment by B-Hartmann** [comment]
Is there a solution for this already? When accessing data on DCOR that has a Shape-In generated "image_bg" via Shape-Out, the following error messages appear:
I know that Shape-Out in general can handle background images, it seems to be that the support in DCOR/dclab is incomplete.
```
Unhandled exception in Shape-Out version 2.11.0:
Traceback (most recent call last):
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\quick_view\qv_main.py", line 530, in plot
    self.on_tool()
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\quick_view\qv_main.py", line 494, in on_tool
    self.on_event_scatter_update()
  File "shapeout2\gui\quick_view\qv_main.py", line 345, in on_event_scatter_update
    self.show_event(event - 1)
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\quick_view\qv_main.py", line 567, in show_event
    cellimg, imkw = self.get_event_image(ds, event)
  File "shapeout2\gui\quick_view\qv_main.py", line 245, in get_event_image
    bgimg = ds["image_bg"][event].astype(np.int16)
  File "dclab\rtdc_dataset\fmt_hierarchy.py", line 48, in __getitem__
  File "dclab\rtdc_dataset\fmt_hierarchy.py", line 48, in __getitem__
  File "dclab\rtdc_dataset\core.py", line 91, in __getitem__
  File "dclab\rtdc_dataset\fmt_dcor\features.py", line 169, in __getitem__
ValueError: No DCOR handler for feature 'image_bg'!
```

And when clicking on an event in the quickview the same thing:
```
Unhandled exception in Shape-Out version 2.11.0:
Traceback (most recent call last):
  File "shapeout2\gui\quick_view\qv_main.py", line 320, in on_event_scatter_clicked
    self.show_event(ds_idx)
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\quick_view\qv_main.py", line 567, in show_event
    cellimg, imkw = self.get_event_image(ds, event)
  File "shapeout2\gui\quick_view\qv_main.py", line 245, in get_event_image
    bgimg = ds["image_bg"][event].astype(np.int16)
  File "dclab\rtdc_dataset\fmt_hierarchy.py", line 48, in __getitem__
  File "dclab\rtdc_dataset\fmt_hierarchy.py", line 48, in __getitem__
  File "dclab\rtdc_dataset\core.py", line 91, in __getitem__
 File "dclab\rtdc_dataset\fmt_dcor\features.py", line 169, in __getitem__
ValueError: No DCOR handler for feature 'image_bg'!
```

**Comment by paulmueller** [comment]
@B-Hartmann Yes, this is not supported yet by DCOR, please create an issue here: https://github.com/DCOR-dev/ckanext-dc_serve/issues

**Comment by paulmueller** [comment]
@maxschloegel Since you are moving away from this approach and instead are using the background data directly, can this issue here be closed?

**Comment by maxschloegel** [comment]
Yes, this can definitely be closed! Thanks!
