### ISSUE TITLE
Deal with TTL for DCOR basin-based feature data

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/dclab#244]
The `dcserv` version 2 API generates a pre-signed URL for accessing a resource via the HTTP format. However, this pre-signed URL has a finite lifetime after which it becomes invalid. The DCOR file format should identify the lifetime and replace the basins automatically upon expiration.

**Comment by paulmueller** [comment]
Here is one of the error messages that may appear in Shape-Out 2

```python
Unhandled exception in Shape-Out version 2.15.0:
Traceback (most recent call last):
  File "/home/paul/repos/ShapeOut2/shapeout2/gui/quick_view/qv_main.py", line 367, in on_event_scatter_hover
    cellimg, imkw = self.get_event_image(self.rtdc_ds, event)
  File "/home/paul/repos/ShapeOut2/shapeout2/gui/quick_view/qv_main.py", line 261, in get_event_image
    cellimg = ds["image"][event]
  File "/home/paul/repos/dclab/dclab/rtdc_dataset/fmt_hierarchy/events.py", line 51, in __getitem__
    return hp[self.feat][pidx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/paul/repos/ShapeOut2/.env/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 758, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 376, in h5py._selector.Reader.read
OSError: Can't read data (wrong B-tree signature)
```

**Comment by paulmueller** [comment]
Probably related error message:

![Image](https://github.com/user-attachments/assets/8d44e3b0-1380-4de5-a9f3-148cef0eb87b)
